### ISSUE TITLE
Have a non-strongname SE.Redis dependency

### ISSUE THREAD

**Issue by CrescentFresh** [jmenziessmith/TagCache.Redis#11]
Is there a technical reason why StackExchange.Redis.StrongName was chosen (vs StackExchange.Redis)?

The issue we are having is we cannot use this package and interop with our existing SE.Redis-dependent code (we have no need for strongly signed dependencies).

For example:

`InHouseRedisUtil.dll` (depends on StackExchange.Redis):

    void TryRedis(Action action)
    {
      try
      {
        action();
      }
      catch(StackExchange.Redis.RedisConnectionException e) // <-- VANILLA SE.Redis here
      {
        // bunch of custom logic to requeue the operation,
        // avoid loss of data, etc, etc
      }
    }

Application code (depends on TagCache.Redis.dll and InHouseRedisUtil.dll):

    InHouseRedisUtil.TryRedis(() => SomeTagCacheRedisOperation());

The two codebases cannot interop even though it's the exact same SE.Redis code underneath.

**Comment by jmenziessmith** [comment]
It should not be the strongname version. Would you like to submit a pr to update all the nuget packages?

**Comment by CrescentFresh** [comment]
I'm on it. Note that this will affect all TagCache.Redis.XXX implementations in this source tree.

**Comment by jmenziessmith** [comment]
I have merged your changes and released a new version (1.0.0.1) to nuget.

Thanks for the help.
