### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by fnicollier** [jmenziessmith/TagCache.Redis#7]
Hi,

So we have a good selection of serializers, migrated to StackExchange and good test coverage.
What do you suggest are the next steps?

I would personally love to be able to use Protobuf without having to manually decorate every cached object so I'm going to try to see if using reflection to setup the serialization is worth it.

I guess there is still a bit of cleaning-up/refactoring we can do but as it is, it's working well in tests on my applications.

After that I guess it would be great if someone jumped in to make a small GitHub page to showcase the  library and how to use it.

Except for NCache (which is commercial), there aren't many .NET caching libraries that support tags so there's that.

**Comment by fnicollier** [comment]
Sweet!

**Comment by fnicollier** [comment]
I'll be decoupling my Autoprotobuf library from my Protobuf serializer to make it cleaner, purely optional and interchangeable.

**Comment by fnicollier** [comment]
I'll be adding Async methods to RedisCacheItemProvider.

**Comment by fnicollier** [comment]
NCache went open source last week. I'll compare performances with TagCache to see how they match up.

**Comment by jmenziessmith** [comment]
Thanks, that would be interesting to see. From their docs, I'm not sure if tagging is supported in the open source version : http://www.alachisoft.com/ncache/edition-comparison.html

**Comment by fnicollier** [comment]
You are right. From your link it seems that tagging and other features are not supported in their open sourced version.
