### ISSUE TITLE
Do we need to wrap cached items in a RedisCacheItem?

### ISSUE THREAD

**Issue by fnicollier** [jmenziessmith/TagCache.Redis#9]
I'm working out some issues with my AutoProtobuf library, specifically support for DataTable and other things. I was wondering if we could do without wrapping items inside a RedisCacheItem.

It would save a tiny bit of overhead, allow using specialized serializers like protobuf-net-data. RedisCacheItem is not exactly indispensable in the current implementation and adds a few headaches including the attribute decoration issue that you want to solve with a factory.

**Comment by CrescentFresh** [comment]
Expiry could be accomplished with redis' built-in [ttl](http://redis.io/commands/ttl) value.

Tags can be stored in another key (as they are in the current implementation).

RedisCacheItem is dispensable far as I can tell. Large refactoring to remove it as you say @fnicollier .
